version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - file
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - directory

hooks:
    BeforeInstall:
     - location: scripts/install_dependencies.sh
       timeout: 300
       runas: ubuntu
    AfterInstall:
     - location: scripts/npm_setup.sh
       timeout: 300
       runas: ubuntu
    
